import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import Components from 'unplugin-vue-components/vite'
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
import { resolve } from 'path'

// Generated by Copilot
// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    // Element Plus 组件与 v-loading 指令按需引入 JS；样式仍在 main.js 全量引入，保证与项目覆盖样式的层叠顺序不变
    Components({
      resolvers: [ElementPlusResolver({ importStyle: false })],
      dts: false
    })
  ],
  test: {
    environment: 'jsdom',
    include: ['src/**/*.test.js']
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, 'src')
    }
  },
  server: {
    host: true, // 监听所有网卡地址，允许局域网访问 Generated by Copilot
    // 优先使用外部指定的 PORT（如预览工具分配的端口），默认 5174
    port: Number(process.env.PORT) || 5174,
    // 外部指定端口时不自动打开浏览器
    open: !process.env.PORT,
    // 配置代理解决跨域问题
    proxy: {
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
        secure: false
      }
    }
  }
})
