<template>
  <div class="page-container">
    <!-- Generated by Copilot -->
    <PageHeader subtitle="覆盖全国仓储节点的实时履约能力视图">
      <template #actions>
        <el-button v-perm="'sys:warehouse:add'" type="primary" :icon="Plus" @click="openCreate">新增仓库</el-button>
      </template>
    </PageHeader>

    <!-- 搜索筛选区域 -->
    <SearchPanel :model="query" :action-span="6" @search="search" @reset="reset">
      <el-col :span="6">
        <el-form-item label="仓库名称">
          <el-input v-model="query.warehouseName" placeholder="请输入仓库名称，回车查询" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="6">
        <el-form-item label="仓库编码">
          <el-input v-model="query.warehouseCode" placeholder="请输入仓库编码，回车查询" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="6">
        <el-form-item label="状态">
          <el-select v-model="query.status" placeholder="全部" clearable style="width: 100%" @change="search">
            <el-option v-for="s in ENABLE_STATUS" :key="s.value" :label="s.label" :value="s.value" />
          </el-select>
        </el-form-item>
      </el-col>
    </SearchPanel>

    <!-- 仓库列表 -->
    <el-card class="table-card">
      <TableToolbar :loading="loading" @refresh="reload" />
      <el-table v-loading="loading" :data="list" border stripe highlight-current-row>
        <el-table-column type="index" :index="rowIndex(page)" label="#" width="60" align="center" />
        <el-table-column
          prop="warehouseCode"
          label="仓库编码"
          width="120"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column
          prop="warehouseName"
          label="仓库名称"
          width="150"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column prop="province" label="省份" width="100" show-overflow-tooltip :formatter="tableDash" />
        <el-table-column prop="city" label="城市" width="100" show-overflow-tooltip :formatter="tableDash" />
        <el-table-column
          prop="warehouseAddress"
          label="仓库地址"
          min-width="200"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column prop="managerName" label="负责人" width="100" show-overflow-tooltip :formatter="tableDash" />
        <el-table-column prop="managerPhone" label="联系电话" width="120" :formatter="tableDash" />
        <el-table-column prop="status" label="状态" width="80">
          <template #default="{ row }">
            <el-tag :type="statusOf(row.status).type">
              {{ statusOf(row.status).label }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="190" fixed="right" align="center">
          <template #default="{ row }"><RowActions :actions="rowActions(row)" /></template>
        </el-table-column>
      </el-table>

      <!-- 分页：v-model 先更新页码 / 条数，change 时统一重新请求 -->
      <ListPagination v-model:current="page.current" v-model:size="page.size" :total="total" @change="reload" />
    </el-card>

    <!-- 新增/编辑对话框 -->
    <el-dialog
      v-model="showAddDialog"
      :title="editingWarehouse ? '编辑仓库' : '新增仓库'"
      width="800px"
      destroy-on-close
    >
      <el-form ref="warehouseFormRef" :model="warehouseForm" :rules="warehouseRules" label-width="100px">
        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="仓库编码" prop="warehouseCode">
              <el-input v-model="warehouseForm.warehouseCode" placeholder="请输入仓库编码" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="仓库名称" prop="warehouseName">
              <el-input v-model="warehouseForm.warehouseName" placeholder="请输入仓库名称" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="负责人" prop="managerName">
              <el-input v-model="warehouseForm.managerName" placeholder="请输入负责人姓名" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="联系电话" prop="managerPhone">
              <el-input v-model="warehouseForm.managerPhone" placeholder="请输入联系电话" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="省份" prop="province">
              <ProvinceSelect v-model="warehouseForm.province" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="城市" prop="city">
              <el-input v-model="warehouseForm.city" placeholder="请输入城市" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-form-item label="仓库地址" prop="warehouseAddress">
          <el-input v-model="warehouseForm.warehouseAddress" placeholder="请输入详细地址" />
        </el-form-item>

        <el-row :gutter="20">
          <el-col :span="12">
            <el-form-item label="经度" prop="longitude">
              <el-input v-model="warehouseForm.longitude" placeholder="请输入经度" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="纬度" prop="latitude">
              <el-input v-model="warehouseForm.latitude" placeholder="请输入纬度" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-form-item label="仓库描述">
          <el-input v-model="warehouseForm.warehouseDesc" type="textarea" :rows="3" placeholder="请输入仓库描述信息" />
        </el-form-item>

        <el-form-item label="状态" prop="status">
          <el-radio-group v-model="warehouseForm.status">
            <el-radio v-for="s in ENABLE_STATUS" :key="s.value" :value="s.value">{{ s.label }}</el-radio>
          </el-radio-group>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleCancel">取消</el-button>
        <el-button type="primary" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>

    <!-- 详情对话框 -->
    <el-dialog v-model="showDetailDialog" title="仓库详情" width="800px">
      <el-descriptions :column="2" border>
        <el-descriptions-item label="仓库编码">{{ dash(currentWarehouse.warehouseCode) }}</el-descriptions-item>
        <el-descriptions-item label="仓库名称">{{ dash(currentWarehouse.warehouseName) }}</el-descriptions-item>
        <el-descriptions-item label="负责人">{{ dash(currentWarehouse.managerName) }}</el-descriptions-item>
        <el-descriptions-item label="联系电话">{{ dash(currentWarehouse.managerPhone) }}</el-descriptions-item>
        <el-descriptions-item label="省份">{{ dash(currentWarehouse.province) }}</el-descriptions-item>
        <el-descriptions-item label="城市">{{ dash(currentWarehouse.city) }}</el-descriptions-item>
        <el-descriptions-item label="经度">{{ dash(currentWarehouse.longitude) }}</el-descriptions-item>
        <el-descriptions-item label="纬度">{{ dash(currentWarehouse.latitude) }}</el-descriptions-item>
        <el-descriptions-item label="仓库地址" :span="2">{{
          dash(currentWarehouse.warehouseAddress)
        }}</el-descriptions-item>
        <el-descriptions-item label="仓库描述" :span="2">{{
          dash(currentWarehouse.warehouseDesc)
        }}</el-descriptions-item>
        <el-descriptions-item label="状态">
          <el-tag :type="statusOf(currentWarehouse.status).type">
            {{ statusOf(currentWarehouse.status).label }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item label="创建时间">{{ formatDateTime(currentWarehouse.createTime) }}</el-descriptions-item>
      </el-descriptions>
      <template #footer>
        <el-button @click="showDetailDialog = false">关闭</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { warehouseApi } from '@/api'
import ProvinceSelect from '@/components/ProvinceSelect.vue'
import PageHeader from '@/components/list-page/PageHeader.vue'
import SearchPanel from '@/components/list-page/SearchPanel.vue'
import TableToolbar from '@/components/list-page/TableToolbar.vue'
import ListPagination from '@/components/list-page/ListPagination.vue'
import RowActions from '@/components/RowActions.vue'
import { useServerList } from '@/composables/useServerList'
import { confirmAction } from '@/utils/confirm'
import { formatDateTime } from '@/utils'
import { dash, tableDash, rowIndex } from '@/utils/format'
import { useRefDataStore } from '@/stores/refData'
import { ENABLE_STATUS } from '@/constants/dict'

// Generated by Copilot
const refData = useRefDataStore()
// 与原逻辑一致：status 非 1 均按禁用展示
const statusOf = (status) => ENABLE_STATUS.find((s) => s.value === (status === 1 ? 1 : 0))
// 操作按钮文案：启用中显示“禁用”，否则显示“启用”
const toggleLabel = (status) => statusOf(status === 1 ? 0 : 1).label
const showAddDialog = ref(false)
const editingWarehouse = ref(null)
const warehouseFormRef = ref()

// 服务端分页：筛选字段与后端 POST /warehouse/list 请求体同名，空值不传
const { query, page, list, total, loading, search, reset, reload } = useServerList(
  (p) => warehouseApi.getWarehouseList(p),
  { warehouseName: '', warehouseCode: '', status: null }
)

// 仓库表单
const warehouseForm = reactive({
  warehouseCode: '',
  warehouseName: '',
  warehouseAddress: '',
  managerName: '',
  managerPhone: '',
  status: 1,
  province: '',
  city: '',
  longitude: '',
  latitude: '',
  warehouseDesc: ''
})

// 表单验证规则
const warehouseRules = {
  warehouseCode: [{ required: true, message: '请输入仓库编码', trigger: 'blur' }],
  warehouseName: [{ required: true, message: '请输入仓库名称', trigger: 'blur' }],
  warehouseAddress: [{ required: true, message: '请输入仓库地址', trigger: 'blur' }],
  managerName: [{ required: true, message: '请输入负责人姓名', trigger: 'blur' }],
  managerPhone: [
    { required: true, message: '请输入联系电话', trigger: 'blur' },
    { pattern: /^1[3-9]\d{9}$/, message: '请输入正确的手机号码', trigger: 'blur' }
  ],
  province: [{ required: true, message: '请选择省份', trigger: 'change' }],
  city: [{ required: true, message: '请选择城市', trigger: 'change' }],
  longitude: [
    { pattern: /^-?((0|1?[0-7]?[0-9]|180)(\.\d{1,6})?)?$/, message: '请输入正确的经度(-180到180)', trigger: 'blur' }
  ],
  latitude: [
    {
      pattern: /^-?((0|[1-8]?[0-9])(\.\d{1,6})?|90(\.0{1,6})?)$/,
      message: '请输入正确的纬度(-90到90)',
      trigger: 'blur'
    }
  ]
}

// 新增：先清空，避免残留上一次编辑的数据导致误更新旧仓库
const openCreate = () => {
  resetForm()
  showAddDialog.value = true
}

const handleEdit = (row) => {
  editingWarehouse.value = row
  Object.keys(warehouseForm).forEach((key) => {
    warehouseForm[key] = row[key]
  })
  showAddDialog.value = true
}

// 查看详情
const showDetailDialog = ref(false)
const currentWarehouse = ref({})

const handleView = async (row) => {
  try {
    loading.value = true
    const result = await warehouseApi.getWarehouseDetail(row.id)
    currentWarehouse.value = result || row
    showDetailDialog.value = true
  } catch (error) {
    console.error('获取仓库详情失败:', error)
    // 如果API失败，使用行数据作为备选
    currentWarehouse.value = row
    showDetailDialog.value = true
  } finally {
    loading.value = false
  }
}

// 仓库变更后，其他页面缓存的仓库下拉需重新拉取
const afterChange = () => {
  refData.invalidate('warehouses')
  reload()
}

// 状态变更：启用中则禁用，否则启用
const handleStatusChange = (row) => {
  const action = toggleLabel(row.status)
  return confirmAction(
    `确定要${action}仓库"${row.warehouseName}"吗？`,
    async () => {
      loading.value = true
      try {
        await (row.status === 1 ? warehouseApi.disableWarehouse(row.id) : warehouseApi.enableWarehouse(row.id))
      } finally {
        loading.value = false
      }
    },
    { title: '确认操作', successText: `${action}成功`, onSuccess: afterChange }
  )
}

// 保存
const handleSave = async () => {
  // 校验失败时 validate() 会 reject，单独处理，避免落入下方 catch
  if (!(await warehouseFormRef.value.validate().catch(() => false))) return
  try {
    loading.value = true

    if (editingWarehouse.value) {
      // 编辑模式
      await warehouseApi.updateWarehouse(editingWarehouse.value.id, warehouseForm)
      ElMessage.success('编辑成功')
    } else {
      // 新增模式
      await warehouseApi.createWarehouse(warehouseForm)
      ElMessage.success('新增成功')
    }

    showAddDialog.value = false
    resetForm()
    afterChange()
  } catch (error) {
    console.error('保存失败:', error)
  } finally {
    loading.value = false
  }
}

// 重置表单
const resetForm = () => {
  Object.keys(warehouseForm).forEach((key) => {
    if (key === 'status') {
      warehouseForm[key] = 1
    } else {
      warehouseForm[key] = ''
    }
  })
  editingWarehouse.value = null
  warehouseFormRef.value?.clearValidate()
}

// 取消操作
const handleCancel = () => {
  showAddDialog.value = false
  resetForm()
}

// 行操作：详情 > 编辑 > 启用/禁用（文案与颜色随状态切换）
const rowActions = (row) => [
  { label: '详情', onClick: () => handleView(row) },
  { label: '编辑', perm: 'sys:warehouse:update', onClick: () => handleEdit(row) },
  {
    label: toggleLabel(row.status),
    perm: 'sys:warehouse:update',
    type: row.status === 1 ? 'danger' : 'success',
    onClick: () => handleStatusChange(row)
  }
]

onMounted(reload)
</script>
