<template>
  <div class="page-container master-data-page">
    <!-- Generated by Copilot -->
    <div class="page-header">
      <div class="header-title">
        <h2>物料管理</h2>
        <p class="page-subtitle">统一维护 SKU 主数据，保障供应链协同一致</p>
      </div>
      <div class="header-actions">
        <el-button v-perm="'sys:material:add'" type="primary" @click="handleCreate">
          <el-icon><Plus /></el-icon>
          新增物料
        </el-button>
      </div>
    </div>

    <el-card class="search-card">
      <el-form :model="searchForm" label-position="top" class="search-form">
        <el-row :gutter="16">
          <el-col :span="6">
            <el-form-item label="物料名称">
              <el-input v-model="searchForm.materialName" placeholder="请输入物料名称" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="物料编码">
              <el-input v-model="searchForm.materialCode" placeholder="请输入物料编码" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="6">
            <el-form-item label="物料类型">
              <el-input v-model="searchForm.materialType" placeholder="请输入物料类型" clearable />
            </el-form-item>
          </el-col>
          <el-col :span="6" class="search-actions">
            <el-space :size="12">
              <el-button type="primary" @click="handleSearch">执行筛选</el-button>
              <el-button @click="handleReset">重置条件</el-button>
            </el-space>
          </el-col>
        </el-row>
      </el-form>
    </el-card>

    <el-card class="table-card">
      <div class="table-toolbar">
        <div class="toolbar-info">
          <span class="toolbar-title">物料清单</span>
          <span class="toolbar-desc">共 {{ pagination.total }} 条数据，确保主数据完整准确</span>
        </div>
        <el-space :size="12">
          <el-button type="primary" link @click="getMaterialList">
            <el-icon><Refresh /></el-icon>
            刷新数据
          </el-button>
        </el-space>
      </div>

      <el-table v-loading="loading" :data="materialList" border stripe highlight-current-row>
        <el-table-column prop="materialCode" label="物料编码" width="140" show-overflow-tooltip />
        <el-table-column prop="materialName" label="物料名称" width="160" show-overflow-tooltip />
        <el-table-column prop="materialType" label="物料类型" width="120" show-overflow-tooltip />
        <el-table-column prop="unit" label="计量单位" width="100" />
        <el-table-column prop="brand" label="品牌" width="120" show-overflow-tooltip />
        <el-table-column prop="origin" label="产地" width="120" show-overflow-tooltip />
        <el-table-column prop="barcode" label="条形码" width="160" show-overflow-tooltip />
        <el-table-column prop="specification" label="规格型号" min-width="160" show-overflow-tooltip />
        <el-table-column prop="materialDesc" label="物料描述" min-width="200" show-overflow-tooltip />
        <el-table-column label="操作" width="220" fixed="right">
          <template #default="{ row }">
            <el-button v-perm="'sys:material:update'" type="primary" link @click="handleEdit(row)">编辑</el-button>
            <el-divider direction="vertical" />
            <el-button type="primary" link @click="handleView(row)">详情</el-button>
            <el-divider direction="vertical" />
            <el-button v-perm="'sys:material:delete'" type="danger" link @click="handleDelete(row)">删除</el-button>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        v-model:current-page="pagination.currentPage"
        v-model:page-size="pagination.pageSize"
        :page-sizes="[10, 20, 50, 100]"
        :total="pagination.total"
        layout="total, sizes, prev, pager, next, jumper"
        @size-change="handleSizeChange"
        @current-change="handleCurrentChange"
      />
    </el-card>

    <el-dialog v-model="showEditorDialog" :title="editingMaterial ? '编辑物料' : '新增物料'" width="700px">
      <el-form ref="materialFormRef" :model="materialForm" :rules="materialRules" label-width="100px">
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="物料编码" prop="materialCode">
              <el-input v-model="materialForm.materialCode" placeholder="请输入物料编码" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="物料名称" prop="materialName">
              <el-input v-model="materialForm.materialName" placeholder="请输入物料名称" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="物料类型" prop="materialType">
              <el-input v-model="materialForm.materialType" placeholder="请输入物料类型" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="计量单位" prop="unit">
              <el-input v-model="materialForm.unit" placeholder="请输入计量单位" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="品牌" prop="brand">
              <el-input v-model="materialForm.brand" placeholder="请输入品牌" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="产地" prop="origin">
              <el-input v-model="materialForm.origin" placeholder="请输入产地" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="条形码" prop="barcode">
              <el-input v-model="materialForm.barcode" placeholder="请输入条形码" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="规格型号" prop="specification">
              <el-input v-model="materialForm.specification" placeholder="请输入规格型号" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-form-item label="物料描述" prop="materialDesc">
          <el-input v-model="materialForm.materialDesc" type="textarea" :rows="3" placeholder="请输入物料描述" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleCancel">取消</el-button>
        <el-button type="primary" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>

    <el-drawer v-model="showDetailDrawer" title="物料详情" size="520px">
      <el-descriptions :column="1" border>
        <el-descriptions-item label="物料编码">{{ currentMaterial.materialCode }}</el-descriptions-item>
        <el-descriptions-item label="物料名称">{{ currentMaterial.materialName }}</el-descriptions-item>
        <el-descriptions-item label="物料类型">{{ currentMaterial.materialType }}</el-descriptions-item>
        <el-descriptions-item label="计量单位">{{ currentMaterial.unit }}</el-descriptions-item>
        <el-descriptions-item label="品牌">{{ currentMaterial.brand || '—' }}</el-descriptions-item>
        <el-descriptions-item label="产地">{{ currentMaterial.origin || '—' }}</el-descriptions-item>
        <el-descriptions-item label="条形码">{{ currentMaterial.barcode || '—' }}</el-descriptions-item>
        <el-descriptions-item label="规格型号">{{ currentMaterial.specification || '—' }}</el-descriptions-item>
        <el-descriptions-item label="物料描述">{{ currentMaterial.materialDesc || '—' }}</el-descriptions-item>
      </el-descriptions>
    </el-drawer>
  </div>
</template>

<script setup>
// Generated by Copilot
import { ref, reactive, computed, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus, Refresh } from '@element-plus/icons-vue'
import { materialApi } from '@/api'
import { confirmAction } from '@/utils/confirm'
import { useRefDataStore } from '@/stores/refData'

const refData = useRefDataStore()

const loading = ref(false)
const materialList = ref([])

const searchForm = reactive({
  materialName: '',
  materialCode: '',
  materialType: ''
})

const pagination = reactive({
  currentPage: 1,
  pageSize: 10,
  total: 0
})

const materialFormRef = ref()
const showEditorDialog = ref(false)
const editingMaterial = ref(null)

const materialForm = reactive({
  materialCode: '',
  materialName: '',
  materialType: '',
  unit: '',
  brand: '',
  origin: '',
  barcode: '',
  specification: '',
  materialDesc: ''
})

const materialRules = {
  materialCode: [{ required: true, message: '请输入物料编码', trigger: 'blur' }],
  materialName: [{ required: true, message: '请输入物料名称', trigger: 'blur' }],
  materialType: [{ required: true, message: '请输入物料类型', trigger: 'blur' }],
  unit: [{ required: true, message: '请输入计量单位', trigger: 'blur' }]
}

const showDetailDrawer = ref(false)
const currentMaterial = ref({})

const sanitizedSearchParams = computed(() => {
  return {
    pageNum: pagination.currentPage,
    pageSize: pagination.pageSize,
    materialName: searchForm.materialName?.trim() || undefined,
    materialCode: searchForm.materialCode?.trim() || undefined,
    materialType: searchForm.materialType?.trim() || undefined
  }
})

// 后端返回 PageResult：{ records, total, current, size }
const getMaterialList = async () => {
  try {
    loading.value = true
    const payload = { ...sanitizedSearchParams.value }
    Object.keys(payload).forEach((key) => {
      if (payload[key] === undefined) {
        delete payload[key]
      }
    })

    const page = await materialApi.getMaterialList(payload)
    materialList.value = page?.records || []
    pagination.total = Number(page?.total) || 0
  } catch (error) {
    console.error('获取物料列表失败:', error)
    materialList.value = []
    pagination.total = 0
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  pagination.currentPage = 1
  getMaterialList()
}

const handleReset = () => {
  Object.keys(searchForm).forEach((key) => {
    searchForm[key] = ''
  })
  pagination.currentPage = 1
  getMaterialList()
}

const handleSizeChange = (val) => {
  pagination.pageSize = val
  pagination.currentPage = 1
  getMaterialList()
}

const handleCurrentChange = (val) => {
  pagination.currentPage = val
  getMaterialList()
}

const handleCreate = () => {
  editingMaterial.value = null
  resetForm()
  showEditorDialog.value = true
}

const handleEdit = async (row) => {
  try {
    loading.value = true
    const detail = await materialApi.getMaterialDetail(row.id)
    Object.keys(materialForm).forEach((key) => {
      materialForm[key] = detail?.[key] ?? ''
    })
    editingMaterial.value = detail || row
    showEditorDialog.value = true
  } catch (error) {
    console.error('获取物料详情失败:', error)
  } finally {
    loading.value = false
  }
}

const handleView = async (row) => {
  try {
    loading.value = true
    const detail = await materialApi.getMaterialDetail(row.id)
    currentMaterial.value = detail || row
    showDetailDrawer.value = true
  } catch (error) {
    console.error('获取物料详情失败:', error)
    currentMaterial.value = row
    showDetailDrawer.value = true
  } finally {
    loading.value = false
  }
}

// 物料变更后，其他页面缓存的物料下拉需重新拉取
const afterChange = () => {
  refData.invalidate('materials')
  getMaterialList()
}

const handleDelete = (row) =>
  confirmAction(
    `确定要删除物料“${row.materialName}”吗？`,
    async () => {
      loading.value = true
      try {
        await materialApi.deleteMaterial(row.id)
      } finally {
        loading.value = false
      }
    },
    { title: '删除确认', successText: '删除成功', onSuccess: afterChange }
  )

const handleSave = async () => {
  // 校验失败时 validate() 会 reject，单独处理，避免落入下方 catch
  if (!(await materialFormRef.value.validate().catch(() => false))) return
  try {
    loading.value = true

    if (editingMaterial.value?.id) {
      await materialApi.updateMaterial(editingMaterial.value.id, materialForm)
      ElMessage.success('物料更新成功')
    } else {
      await materialApi.createMaterial(materialForm)
      ElMessage.success('物料新增成功')
    }

    showEditorDialog.value = false
    resetForm()
    afterChange()
  } catch (error) {
    console.error('保存物料失败:', error)
  } finally {
    loading.value = false
  }
}

const handleCancel = () => {
  showEditorDialog.value = false
  resetForm()
}

const resetForm = () => {
  Object.keys(materialForm).forEach((key) => {
    materialForm[key] = ''
  })
  editingMaterial.value = null
  materialFormRef.value?.clearValidate()
}

onMounted(() => {
  getMaterialList()
})
</script>
