<template>
  <div class="page-container">
    <!-- Generated by Copilot -->
    <PageHeader subtitle="统一维护 SKU 主数据，保障供应链协同一致">
      <template #actions>
        <el-button v-perm="'sys:material:add'" type="primary" :icon="Plus" @click="handleCreate">新增物料</el-button>
      </template>
    </PageHeader>

    <SearchPanel :model="query" :action-span="6" @search="search" @reset="reset">
      <el-col :span="6">
        <el-form-item label="物料名称">
          <el-input v-model="query.materialName" placeholder="请输入物料名称，回车查询" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="6">
        <el-form-item label="物料编码">
          <el-input v-model="query.materialCode" placeholder="请输入物料编码，回车查询" clearable />
        </el-form-item>
      </el-col>
      <el-col :span="6">
        <el-form-item label="物料类型">
          <el-input v-model="query.materialType" placeholder="请输入物料类型，回车查询" clearable />
        </el-form-item>
      </el-col>
    </SearchPanel>

    <el-card class="table-card">
      <TableToolbar :loading="loading" @refresh="reload" />

      <el-table v-loading="loading" :data="list" border stripe highlight-current-row>
        <el-table-column type="index" :index="rowIndex(page)" label="#" width="60" align="center" />
        <el-table-column
          prop="materialCode"
          label="物料编码"
          width="140"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column
          prop="materialName"
          label="物料名称"
          width="160"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column
          prop="materialType"
          label="物料类型"
          width="120"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column prop="unit" label="计量单位" width="100" :formatter="tableDash" />
        <el-table-column prop="brand" label="品牌" width="120" show-overflow-tooltip :formatter="tableDash" />
        <el-table-column prop="origin" label="产地" width="120" show-overflow-tooltip :formatter="tableDash" />
        <el-table-column prop="barcode" label="条形码" width="160" show-overflow-tooltip :formatter="tableDash" />
        <el-table-column
          prop="specification"
          label="规格型号"
          min-width="160"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column
          prop="materialDesc"
          label="物料描述"
          min-width="200"
          show-overflow-tooltip
          :formatter="tableDash"
        />
        <el-table-column label="操作" width="190" fixed="right" align="center">
          <template #default="{ row }"><RowActions :actions="rowActions(row)" /></template>
        </el-table-column>
      </el-table>

      <!-- 分页：v-model 先更新页码 / 条数，change 时统一重新请求 -->
      <ListPagination v-model:current="page.current" v-model:size="page.size" :total="total" @change="reload" />
    </el-card>

    <el-dialog v-model="showEditorDialog" :title="editingMaterial ? '编辑物料' : '新增物料'" width="700px">
      <el-form ref="materialFormRef" :model="materialForm" :rules="materialRules" label-width="100px">
        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="物料编码" prop="materialCode">
              <el-input v-model="materialForm.materialCode" placeholder="请输入物料编码" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="物料名称" prop="materialName">
              <el-input v-model="materialForm.materialName" placeholder="请输入物料名称" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="物料类型" prop="materialType">
              <el-input v-model="materialForm.materialType" placeholder="请输入物料类型" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="计量单位" prop="unit">
              <el-input v-model="materialForm.unit" placeholder="请输入计量单位" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="品牌" prop="brand">
              <el-input v-model="materialForm.brand" placeholder="请输入品牌" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="产地" prop="origin">
              <el-input v-model="materialForm.origin" placeholder="请输入产地" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-row :gutter="16">
          <el-col :span="12">
            <el-form-item label="条形码" prop="barcode">
              <el-input v-model="materialForm.barcode" placeholder="请输入条形码" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="规格型号" prop="specification">
              <el-input v-model="materialForm.specification" placeholder="请输入规格型号" />
            </el-form-item>
          </el-col>
        </el-row>

        <el-form-item label="物料描述" prop="materialDesc">
          <el-input v-model="materialForm.materialDesc" type="textarea" :rows="3" placeholder="请输入物料描述" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleCancel">取消</el-button>
        <el-button type="primary" @click="handleSave">保存</el-button>
      </template>
    </el-dialog>

    <el-drawer v-model="showDetailDrawer" title="物料详情" size="520px">
      <el-descriptions :column="1" border>
        <el-descriptions-item label="物料编码">{{ dash(currentMaterial.materialCode) }}</el-descriptions-item>
        <el-descriptions-item label="物料名称">{{ dash(currentMaterial.materialName) }}</el-descriptions-item>
        <el-descriptions-item label="物料类型">{{ dash(currentMaterial.materialType) }}</el-descriptions-item>
        <el-descriptions-item label="计量单位">{{ dash(currentMaterial.unit) }}</el-descriptions-item>
        <el-descriptions-item label="品牌">{{ dash(currentMaterial.brand) }}</el-descriptions-item>
        <el-descriptions-item label="产地">{{ dash(currentMaterial.origin) }}</el-descriptions-item>
        <el-descriptions-item label="条形码">{{ dash(currentMaterial.barcode) }}</el-descriptions-item>
        <el-descriptions-item label="规格型号">{{ dash(currentMaterial.specification) }}</el-descriptions-item>
        <el-descriptions-item label="物料描述">{{ dash(currentMaterial.materialDesc) }}</el-descriptions-item>
      </el-descriptions>
    </el-drawer>
  </div>
</template>

<script setup>
// Generated by Copilot
import { ref, reactive, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Plus } from '@element-plus/icons-vue'
import { materialApi } from '@/api'
import PageHeader from '@/components/list-page/PageHeader.vue'
import SearchPanel from '@/components/list-page/SearchPanel.vue'
import TableToolbar from '@/components/list-page/TableToolbar.vue'
import ListPagination from '@/components/list-page/ListPagination.vue'
import RowActions from '@/components/RowActions.vue'
import { useServerList } from '@/composables/useServerList'
import { confirmAction } from '@/utils/confirm'
import { dash, tableDash, rowIndex } from '@/utils/format'
import { useRefDataStore } from '@/stores/refData'

const refData = useRefDataStore()

// 服务端分页：后端返回 PageResult，筛选字段与 POST /material/list 请求体同名，空值不传
const { query, page, list, total, loading, search, reset, reload } = useServerList(
  (p) => materialApi.getMaterialList(p),
  { materialName: '', materialCode: '', materialType: '' }
)

const materialFormRef = ref()
const showEditorDialog = ref(false)
const editingMaterial = ref(null)

const materialForm = reactive({
  materialCode: '',
  materialName: '',
  materialType: '',
  unit: '',
  brand: '',
  origin: '',
  barcode: '',
  specification: '',
  materialDesc: ''
})

const materialRules = {
  materialCode: [{ required: true, message: '请输入物料编码', trigger: 'blur' }],
  materialName: [{ required: true, message: '请输入物料名称', trigger: 'blur' }],
  materialType: [{ required: true, message: '请输入物料类型', trigger: 'blur' }],
  unit: [{ required: true, message: '请输入计量单位', trigger: 'blur' }]
}

const showDetailDrawer = ref(false)
const currentMaterial = ref({})

const handleCreate = () => {
  editingMaterial.value = null
  resetForm()
  showEditorDialog.value = true
}

const handleEdit = async (row) => {
  try {
    loading.value = true
    const detail = await materialApi.getMaterialDetail(row.id)
    Object.keys(materialForm).forEach((key) => {
      materialForm[key] = detail?.[key] ?? ''
    })
    editingMaterial.value = detail || row
    showEditorDialog.value = true
  } catch (error) {
    console.error('获取物料详情失败:', error)
  } finally {
    loading.value = false
  }
}

const handleView = async (row) => {
  try {
    loading.value = true
    const detail = await materialApi.getMaterialDetail(row.id)
    currentMaterial.value = detail || row
    showDetailDrawer.value = true
  } catch (error) {
    console.error('获取物料详情失败:', error)
    currentMaterial.value = row
    showDetailDrawer.value = true
  } finally {
    loading.value = false
  }
}

// 物料变更后，其他页面缓存的物料下拉需重新拉取
const afterChange = () => {
  refData.invalidate('materials')
  reload()
}

const handleDelete = (row) =>
  confirmAction(
    `确定要删除物料“${row.materialName}”吗？`,
    async () => {
      loading.value = true
      try {
        await materialApi.deleteMaterial(row.id)
      } finally {
        loading.value = false
      }
    },
    { title: '删除确认', successText: '删除成功', onSuccess: afterChange }
  )

// 行操作：详情 > 编辑；删除为危险操作
const rowActions = (row) => [
  { label: '详情', onClick: () => handleView(row) },
  { label: '编辑', perm: 'sys:material:update', onClick: () => handleEdit(row) },
  { label: '删除', perm: 'sys:material:delete', danger: true, onClick: () => handleDelete(row) }
]

const handleSave = async () => {
  // 校验失败时 validate() 会 reject，单独处理，避免落入下方 catch
  if (!(await materialFormRef.value.validate().catch(() => false))) return
  try {
    loading.value = true

    if (editingMaterial.value?.id) {
      await materialApi.updateMaterial(editingMaterial.value.id, materialForm)
      ElMessage.success('物料更新成功')
    } else {
      await materialApi.createMaterial(materialForm)
      ElMessage.success('物料新增成功')
    }

    showEditorDialog.value = false
    resetForm()
    afterChange()
  } catch (error) {
    console.error('保存物料失败:', error)
  } finally {
    loading.value = false
  }
}

const handleCancel = () => {
  showEditorDialog.value = false
  resetForm()
}

const resetForm = () => {
  Object.keys(materialForm).forEach((key) => {
    materialForm[key] = ''
  })
  editingMaterial.value = null
  materialFormRef.value?.clearValidate()
}

onMounted(reload)
</script>
