<template>
  <el-select 
    :model-value="modelValue"
    :placeholder="placeholder"
    :filterable="filterable"
    :clearable="clearable"
    :disabled="disabled"
    :size="size"
    @update:model-value="handleChange"
  >
    <el-option 
      v-for="option in PROVINCE_OPTIONS" 
      :key="option.value"
      :label="option.label" 
      :value="option.value" 
    />
  </el-select>
</template>

<script setup>
import { PROVINCE_OPTIONS } from '@/constants/regions'

// Generated by Copilot
defineProps({
  modelValue: {
    type: String,
    default: ''
  },
  placeholder: {
    type: String,
    default: '请选择省份'
  },
  filterable: {
    type: Boolean,
    default: true
  },
  clearable: {
    type: Boolean,
    default: true
  },
  disabled: {
    type: Boolean,
    default: false
  },
  size: {
    type: String,
    default: 'default'
  }
})

const emit = defineEmits(['update:modelValue', 'change'])

const handleChange = (value) => {
  emit('update:modelValue', value)
  emit('change', value)
}
</script>

<style scoped>
/* 组件特定样式 */
</style>
