// Generated by Copilot
import MarkdownIt from 'markdown-it'
import DOMPurify from 'dompurify'

// mermaid 体积很大（连带 cytoscape、katex 等），仅在出现 mermaid 代码块时按需加载并初始化一次
let mermaidPromise = null
const loadMermaid = () => {
  if (!mermaidPromise) {
    mermaidPromise = import('mermaid').then(({ default: mermaid }) => {
      mermaid.initialize({
        startOnLoad: false,
        securityLevel: 'strict',
        theme: 'default'
      })
      return mermaid
    })
    // 加载失败（如网络中断）时允许下次重试
    mermaidPromise.catch(() => { mermaidPromise = null })
  }
  return mermaidPromise
}

const md = new MarkdownIt({
  html: false, // 禁止原始 HTML，降低 XSS 风险
  linkify: true,
  breaks: true
})

// mermaid 代码块先渲染为占位元素，源码经 URI 编码存入 data 属性，待 renderMermaidBlocks 转成 SVG
const defaultFence =
  md.renderer.rules.fence ||
  ((tokens, idx, options, env, self) => self.renderToken(tokens, idx, options))
md.renderer.rules.fence = (tokens, idx, options, env, self) => {
  const token = tokens[idx]
  // 只取语言标记的第一个词并忽略大小写，兼容 ```Mermaid、```mermaid {…} 等写法
  const lang = (token.info || '').trim().split(/\s+/)[0].toLowerCase()
  if (lang === 'mermaid') {
    const encoded = encodeURIComponent(token.content)
    return `<pre class="mermaid-block" data-code="${encoded}">${md.utils.escapeHtml(token.content)}</pre>`
  }
  return defaultFence(tokens, idx, options, env, self)
}

// 链接统一新开页并加 noopener，避免安全隐患
const defaultLinkOpen =
  md.renderer.rules.link_open ||
  ((tokens, idx, options, env, self) => self.renderToken(tokens, idx, options))
md.renderer.rules.link_open = (tokens, idx, options, env, self) => {
  const token = tokens[idx]
  token.attrSet('target', '_blank')
  token.attrSet('rel', 'noopener noreferrer')
  return defaultLinkOpen(tokens, idx, options, env, self)
}

/**
 * 渲染 markdown 文本为安全的 HTML 字符串
 * @param {string} text
 * @returns {string}
 */
export function renderMarkdown(text) {
  if (!text) {
    return ''
  }
  const rawHtml = md.render(String(text))
  return DOMPurify.sanitize(rawHtml, {
    ADD_ATTR: ['target', 'rel']
  })
}

let mermaidSeq = 0

// 渲染失败时在源码块上标注原因（样式里用 ::before 展示），并输出具体错误便于排查
const markFailed = (block, reason, error) => {
  block.dataset.error = reason
  console.warn(`[mermaid] ${reason}`, error?.message || error || '')
}

/**
 * 将容器内尚未渲染的 mermaid 占位块转换为 SVG 图表
 * 失败时保留源码展示，并标注失败原因
 * @param {HTMLElement} container
 */
export async function renderMermaidBlocks(container) {
  if (!container) {
    return
  }
  const blocks = container.querySelectorAll('pre.mermaid-block:not([data-rendered])')
  if (!blocks.length) {
    return
  }
  let mermaid
  try {
    mermaid = await loadMermaid()
  } catch (e) {
    blocks.forEach((block) => markFailed(block, '图表组件加载失败，请刷新页面后重试', e))
    return
  }
  for (const block of blocks) {
    const code = decodeURIComponent(block.dataset.code || '')
    if (!code.trim()) {
      continue
    }
    try {
      // 先校验语法，避免 mermaid 向页面注入错误提示节点
      await mermaid.parse(code)
    } catch (e) {
      markFailed(block, '图表语法有误，已显示源码', e)
      continue
    }
    try {
      const id = `mermaid-chart-${++mermaidSeq}`
      const { svg } = await mermaid.render(id, code)
      const wrap = document.createElement('div')
      wrap.className = 'mermaid-chart'
      wrap.innerHTML = DOMPurify.sanitize(svg, {
        USE_PROFILES: { svg: true, svgFilters: true },
        ADD_TAGS: ['foreignObject'],
        ADD_ATTR: ['dominant-baseline']
      })
      block.replaceWith(wrap)
    } catch (e) {
      // 渲染失败时清理 mermaid 遗留的临时节点，保留源码展示
      const leftover = document.getElementById(`dmermaid-chart-${mermaidSeq}`)
      if (leftover) {
        leftover.remove()
      }
      markFailed(block, '图表渲染失败，已显示源码', e)
    }
  }
}
