<!-- Generated by Copilot -->
<template>
  <div class="chat-page">
    <!-- 顶部工具栏 -->
    <div class="chat-toolbar">
      <div class="toolbar-left">
        <div class="agent-avatar">AI</div>
        <div class="agent-meta">
          <div class="agent-name">智能助手</div>
          <div class="agent-status">
            <span class="status-dot" :class="statusClass"></span>
            <span class="status-text">{{ statusText }}</span>
          </div>
        </div>
      </div>
      <div class="toolbar-right">
        <!-- Generated by Copilot -->
        <el-tooltip content="可选：填写后随消息传给后端" placement="bottom">
          <el-input
            v-model="authToken"
            class="auth-token-input"
            size="small"
            clearable
            show-password
            placeholder="Auth Token（可选）"
          />
        </el-tooltip>
        <el-tooltip content="显示思考过程" placement="bottom">
          <el-switch v-model="returnThought" active-text="思考" size="small" />
        </el-tooltip>
        <el-button size="small" :icon="Refresh" @click="newSession">新会话</el-button>
      </div>
    </div>

    <!-- 消息列表 -->
    <div ref="scrollRef" class="chat-body">
      <div class="chat-inner">
        <div v-if="messages.length === 0" class="chat-empty">
          <div class="empty-icon">💬</div>
          <div class="empty-title">开始和智能助手对话</div>
          <div class="empty-tips">
            <span v-for="tip in quickTips" :key="tip" class="tip-chip" @click="applyTip(tip)">{{ tip }}</span>
          </div>
        </div>

        <ChatMessage
          v-for="msg in messages"
          :key="msg.id"
          :msg="msg"
          :user-initial="userInitial"
          @toggle-thought="msg.thoughtOpen = !msg.thoughtOpen"
        />
      </div>
    </div>

    <!-- 输入区 -->
    <ChatInput v-model="input" :session-id="sessionId" :streaming="isStreaming" @send="send" @stop="stopStreaming" />
  </div>
</template>

<script setup>
import { ref, computed, nextTick } from 'vue'
import { Refresh } from '@element-plus/icons-vue'
import { useUserStore } from '@/stores/user'
import ChatMessage from './ChatMessage.vue'
import ChatInput from './ChatInput.vue'
import { useAgentSocket } from './useAgentSocket'

const userStore = useUserStore()

const input = ref('')
const messages = ref([])
const returnThought = ref(false)
// Generated by Copilot：可选 auth token，填入后随消息带给后端
const authToken = ref('')
const scrollRef = ref(null)

const userId = computed(() => String(userStore.userInfo?.userId || 'u1'))
const userInitial = computed(() => (userStore.displayName || 'U').charAt(0).toUpperCase())

const scrollToBottom = () => {
  nextTick(() => {
    const el = scrollRef.value
    if (el) {
      el.scrollTop = el.scrollHeight
    }
  })
}

const {
  sessionId,
  connState,
  isStreaming,
  sendPrompt,
  stopStreaming,
  resetSession: newSession
} = useAgentSocket({
  messages,
  userId,
  returnThought,
  authToken,
  onUpdate: scrollToBottom
})

const statusClass = computed(
  () =>
    ({
      idle: 'is-idle',
      connecting: 'is-busy',
      streaming: 'is-busy',
      error: 'is-error'
    })[connState.value]
)
const statusText = computed(
  () =>
    ({
      idle: '在线',
      connecting: '连接中…',
      streaming: '回复中…',
      error: '连接异常'
    })[connState.value]
)

const quickTips = ['你能读真实代码吗', '介绍一下这个系统', '帮我查询库存', '入库流程是怎样的']

const applyTip = (tip) => {
  input.value = tip
}

const send = () => {
  const prompt = input.value.trim()
  if (!prompt || isStreaming.value) {
    return
  }
  input.value = ''
  sendPrompt(prompt)
}
</script>

<style scoped>
.chat-page {
  display: flex;
  flex-direction: column;
  height: calc(100vh - 120px);
  min-height: 480px;
  background: #fff;
  border: 1px solid var(--brand-border, #e4e7ed);
  border-radius: 12px;
  overflow: hidden;
}

/* 顶部工具栏 */
.chat-toolbar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 20px;
  border-bottom: 1px solid #eef1f6;
  background: linear-gradient(90deg, #f7f9fc 0%, #fff 100%);
}
.toolbar-left {
  display: flex;
  align-items: center;
  gap: 12px;
}
.agent-avatar {
  width: 38px;
  height: 38px;
  border-radius: 10px;
  background: linear-gradient(135deg, #1765ad 0%, #4a90e2 100%);
  color: #fff;
  font-weight: 700;
  font-size: 13px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.agent-name {
  font-size: 15px;
  font-weight: 600;
  color: #1f2d3d;
}
.agent-status {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-top: 2px;
}
.status-dot {
  width: 7px;
  height: 7px;
  border-radius: 50%;
  background: #34a853;
}
.status-dot.is-busy {
  background: #f59e0b;
  animation: pulse 1s infinite;
}
.status-dot.is-error {
  background: #f56c6c;
}
.status-text {
  font-size: 12px;
  color: #909399;
}
.toolbar-right {
  display: flex;
  align-items: center;
  gap: 14px;
}
/* Generated by Copilot */
.auth-token-input {
  width: 220px;
}

/* 消息区 */
.chat-body {
  flex: 1;
  overflow-y: auto;
  padding: 20px 0;
  background: #f7f9fc;
}
.chat-inner {
  max-width: 1400px;
  width: 100%;
  margin: 0 auto;
  padding: 0 32px;
}
.chat-empty {
  text-align: center;
  padding: 60px 0;
  color: #909399;
}
.empty-icon {
  font-size: 40px;
}
.empty-title {
  margin-top: 12px;
  font-size: 16px;
  color: #606266;
}
.empty-tips {
  margin-top: 20px;
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
  justify-content: center;
}
.tip-chip {
  padding: 7px 14px;
  background: #fff;
  border: 1px solid #e4e7ed;
  border-radius: 16px;
  font-size: 13px;
  color: #606266;
  cursor: pointer;
  transition: all 0.2s;
}
.tip-chip:hover {
  border-color: #1765ad;
  color: #1765ad;
}

@keyframes pulse {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.4;
  }
}
</style>
