<template>
  <div id="app">
    <!-- Generated by Copilot -->
    <router-view />
  </div>
</template>

<script setup>
import { onMounted } from 'vue'
import { useAppStore } from '@/stores'

const appStore = useAppStore()

onMounted(() => {
  // 初始化应用设置
  appStore.initAppSettings()
})
</script>

<style>
/* Generated by Copilot */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body {
  height: 100%;
  font-family: var(--brand-font, 'Inter', 'Segoe UI', 'PingFang SC', sans-serif);
  background-color: var(--brand-bg);
  overflow: hidden;
}

#app {
  height: 100vh;
  width: 100vw;
  overflow: hidden;
  /* 桌面端后台，最小宽度只在此处统一设置 */
  min-width: 1280px;
  background-color: var(--brand-bg);
}

/* 滚动条样式 */
::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

::-webkit-scrollbar-track {
  background: #eef2f8;
  border-radius: 3px;
}

::-webkit-scrollbar-thumb {
  background: rgba(23, 101, 173, 0.35);
  border-radius: 3px;
}

::-webkit-scrollbar-thumb:hover {
  background: rgba(23, 101, 173, 0.55);
}

/* Element Plus 样式覆盖 */
.el-table .cell {
  word-break: keep-all;
}

.el-pagination {
  justify-content: flex-end;
}

.el-container {
  height: 100%;
}

.el-main {
  padding: 0 !important;
}
</style>
