import { createApp } from 'vue'
import { createPinia } from 'pinia'
import { ElMessage, ElMessageBox, provideGlobalConfig } from 'element-plus'
import zhCn from 'element-plus/es/locale/lang/zh-cn'
import 'element-plus/dist/index.css'
import './style.css'
import './styles/common.css'
import App from './App.vue'
import router from './router'
import perm from './directives/perm'

// Generated by Copilot
const app = createApp(App)
const pinia = createPinia()

// 设置页面标题
document.title = import.meta.env.VITE_APP_TITLE || '供应链管理中台'

// Element Plus 按需引入后不再 app.use(ElementPlus)：在 app 级注入中文语言包，
// 并为命令式调用的消息/确认框挂上 app 上下文，否则未显式传按钮文案的确认框会显示英文 OK/Cancel
provideGlobalConfig({ locale: zhCn }, app, true)
app.use(ElMessage)
app.use(ElMessageBox)

app.use(pinia)
app.directive('perm', perm)
app.use(router)
app.mount('#app')
